[project]
name = "barcloudtask"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.2",
    "openai>=2.17.0",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.40.0",
]
